[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Note: Cache exclusions removed to allow redirects to work properly

# PRIORITY 1: Specific HTML to slash redirects (must be first to take precedence)
[[redirects]]
  from = "/articles/wallets.html"
  to = "/articles/wallets/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/handbags.html"
  to = "/articles/handbags/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/backpacks.html"
  to = "/articles/backpacks/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/tote-bags.html"
  to = "/articles/tote-bags/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/carteras.html"
  to = "/es/articulos/carteras/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/bolsos-de-mano.html"
  to = "/es/articulos/bolsos-de-mano/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/mochilas.html"
  to = "/es/articulos/mochilas/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/tote-bags.html"
  to = "/es/articulos/tote-bags/"
  status = 301
  force = true

# PRIORITY 2: General HTML to slash redirects
[[redirects]]
  from = "/articles/*.html"
  to = "/articles/:splat/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/*.html"
  to = "/es/articulos/:splat/"
  status = 301
  force = true

# PRIORITY 2: Quiz page redirects
[[redirects]]
  from = "/quiz/bag-personality.html"
  to = "/quiz/bag-personality/"
  status = 301
  force = true

[[redirects]]
  from = "/quiz/bag-personality/"
  to = "/quiz/bag-personality/index.html"
  status = 200

# PRIORITY 3: Main page serves
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/es/"
  to = "/es/index.html"
  status = 200

# PRIORITY 4: Article index serves
[[redirects]]
  from = "/articles/"
  to = "/articles/index.html"
  status = 200

[[redirects]]
  from = "/es/articulos/"
  to = "/es/articulos/index.html"
  status = 200

# PRIORITY 5: Category index serves
[[redirects]]
  from = "/categories/"
  to = "/categories/index.html"
  status = 200

[[redirects]]
  from = "/es/categorias/"
  to = "/es/categorias/index.html"
  status = 200

# PRIORITY 7: Main page redirects
[[redirects]]
  from = "/privacy-policy.html"
  to = "/privacy-policy/"
  status = 301
  force = true

[[redirects]]
  from = "/affiliate-disclosure.html"
  to = "/affiliate-disclosure/"
  status = 301
  force = true

[[redirects]]
  from = "/es/politica-privacidad.html"
  to = "/es/politica-privacidad/"
  status = 301
  force = true

[[redirects]]
  from = "/es/aviso-afiliados.html"
  to = "/es/aviso-afiliados/"
  status = 301
  force = true

# PRIORITY 8: Category redirects
[[redirects]]
  from = "/categories/*.html"
  to = "/categories/:splat/"
  status = 301
  force = true

[[redirects]]
  from = "/es/categorias/*.html"
  to = "/es/categorias/:splat/"
  status = 301
  force = true

# PRIORITY 9: Category serves (after redirects)
[[redirects]]
  from = "/categories/*/"
  to = "/categories/:splat/index.html"
  status = 200

[[redirects]]
  from = "/es/categorias/*/"
  to = "/es/categorias/:splat/index.html"
  status = 200

# PRIORITY 10: Article serves (after redirects)
[[redirects]]
  from = "/articles/*/"
  to = "/articles/:splat.html"
  status = 200

[[redirects]]
  from = "/es/articulos/*/"
  to = "/es/articulos/:splat.html"
  status = 200

# PRIORITY 11: Main page serves (after redirects)
[[redirects]]
  from = "/privacy-policy/"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/affiliate-disclosure/"
  to = "/affiliate-disclosure.html"
  status = 200

[[redirects]]
  from = "/es/politica-privacidad/"
  to = "/es/politica-privacidad.html"
  status = 200

[[redirects]]
  from = "/es/aviso-afiliados/"
  to = "/es/aviso-afiliados.html"
  status = 200
