[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Note: Cache exclusions removed to allow redirects to work properly

# PRIORITY 1: Individual Article Redirects (English)
# ==================================================
[[redirects]]
  from = "/articles/10-buzzy-it-bags-fall-2025.html"
  to = "/articles/10-buzzy-it-bags-fall-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/3-functional-diaper-bags-moms-2025.html"
  to = "/articles/3-functional-diaper-bags-moms-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/3-functional-university-tote-bags-2025.html"
  to = "/articles/3-functional-university-tote-bags-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/3-popular-amazon-tote-bags-2025.html"
  to = "/articles/3-popular-amazon-tote-bags-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/3-reusable-shopping-tote-bags-2025.html"
  to = "/articles/3-reusable-shopping-tote-bags-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/3-rfid-security-wallets-2025.html"
  to = "/articles/3-rfid-security-wallets-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/3-stylish-professional-backpacks-2025.html"
  to = "/articles/3-stylish-professional-backpacks-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/3-wristlet-wallets-women-2025.html"
  to = "/articles/3-wristlet-wallets-women-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/affordable-elegant-casual-handbags-wedding-guest-2025.html"
  to = "/articles/affordable-elegant-casual-handbags-wedding-guest-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/backpacks.html"
  to = "/articles/backpacks/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/best-durable-stylish-backpacks-2025.html"
  to = "/articles/best-durable-stylish-backpacks-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/best-lightweight-travel-backpacks-2025.html"
  to = "/articles/best-lightweight-travel-backpacks-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/best-wedding-handbags-2025.html"
  to = "/articles/best-wedding-handbags-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/fun-unique-gift-wallets-2025.html"
  to = "/articles/fun-unique-gift-wallets-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/handbags.html"
  to = "/articles/handbags/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/how-to-choose-perfect-handbag-2025.html"
  to = "/articles/how-to-choose-perfect-handbag-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/laptop-backpacks-protection-style-2025.html"
  to = "/articles/laptop-backpacks-protection-style-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/minimalist-daily-bag-2025.html"
  to = "/articles/minimalist-daily-bag-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/top-5-professional-women-wallets-2025.html"
  to = "/articles/top-5-professional-women-wallets-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/tote-bags.html"
  to = "/articles/tote-bags/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/travel-light-adventure-bags-2025.html"
  to = "/articles/travel-light-adventure-bags-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/wallets.html"
  to = "/articles/wallets/"
  status = 301
  force = true

# PRIORITY 2: Main Pages Redirects
# =================================
[[redirects]]
  from = "/es.html"
  to = "/es/"
  status = 301
  force = true

[[redirects]]
  from = "/categories.html"
  to = "/categories/"
  status = 301
  force = true

[[redirects]]
  from = "/es/categorias.html"
  to = "/es/categorias/"
  status = 301
  force = true

# PRIORITY 3: Individual Article Redirects (Spanish)
# ==================================================
[[redirects]]
  from = "/es/articulos/3-bolsos-panales-funcionales-mamas-2025.html"
  to = "/es/articulos/3-bolsos-panales-funcionales-mamas-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/3-carteras-rfid-seguridad-2025.html"
  to = "/es/articulos/3-carteras-rfid-seguridad-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/3-carteras-wristlet-mujeres-2025.html"
  to = "/es/articulos/3-carteras-wristlet-mujeres-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/3-mochilas-profesionales-estilosas-2025.html"
  to = "/es/articulos/3-mochilas-profesionales-estilosas-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/3-tote-bags-funcionales-universidad-2025.html"
  to = "/es/articulos/3-tote-bags-funcionales-universidad-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/3-tote-bags-populares-amazon-2025.html"
  to = "/es/articulos/3-tote-bags-populares-amazon-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/3-tote-bags-reutilizables-compras-2025.html"
  to = "/es/articulos/3-tote-bags-reutilizables-compras-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/best-durable-stylish-backpacks-2025.html"
  to = "/es/articulos/best-durable-stylish-backpacks-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/bolso-minimalista-dia-dia-2025.html"
  to = "/es/articulos/bolso-minimalista-dia-dia-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/bolsos-casual-elegantes-asequibles-invitadas-bodas-2025.html"
  to = "/es/articulos/bolsos-casual-elegantes-asequibles-invitadas-bodas-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/bolsos-de-mano.html"
  to = "/es/articulos/bolsos-de-mano/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/carteras-divertidas-unicas-regalo-2025.html"
  to = "/es/articulos/carteras-divertidas-unicas-regalo-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/carteras.html"
  to = "/es/articulos/carteras/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/como-elegir-bolso-mano-perfecto-2025.html"
  to = "/es/articulos/como-elegir-bolso-mano-perfecto-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/las-mejores-mochilas-mano-viajar-ligero-2025.html"
  to = "/es/articulos/las-mejores-mochilas-mano-viajar-ligero-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/mejores-bolsos-mano-bodas-2025.html"
  to = "/es/articulos/mejores-bolsos-mano-bodas-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/mochilas-para-laptop-proteccion-estilo-2025.html"
  to = "/es/articulos/mochilas-para-laptop-proteccion-estilo-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/mochilas.html"
  to = "/es/articulos/mochilas/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/resistentes-estilo-mejores-mochilas-dia-dia-2025.html"
  to = "/es/articulos/resistentes-estilo-mejores-mochilas-dia-dia-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/top-5-carteras-mujeres-profesionales-2025.html"
  to = "/es/articulos/top-5-carteras-mujeres-profesionales-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/tote-bags.html"
  to = "/es/articulos/tote-bags/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/viajar-ligera-bolsos-aventureras-2025.html"
  to = "/es/articulos/viajar-ligera-bolsos-aventureras-2025/"
  status = 301
  force = true

# PRIORITY 2: General HTML to slash redirects
[[redirects]]
  from = "/articles/*.html"
  to = "/articles/:splat/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/*.html"
  to = "/es/articulos/:splat/"
  status = 301
  force = true

# PRIORITY 2: Quiz page redirects
[[redirects]]
  from = "/quiz/bag-personality.html"
  to = "/quiz/bag-personality/"
  status = 301
  force = true

[[redirects]]
  from = "/quiz/bag-personality/"
  to = "/quiz/bag-personality/index.html"
  status = 200

# PRIORITY 3: Main page serves
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/es/"
  to = "/es/index.html"
  status = 200

# PRIORITY 4: Article index serves
[[redirects]]
  from = "/articles/"
  to = "/articles/index.html"
  status = 200

[[redirects]]
  from = "/es/articulos/"
  to = "/es/articulos/index.html"
  status = 200

# PRIORITY 5: Category index serves
[[redirects]]
  from = "/categories/"
  to = "/categories/index.html"
  status = 200

[[redirects]]
  from = "/es/categorias/"
  to = "/es/categorias/index.html"
  status = 200

# PRIORITY 7: Main page redirects
[[redirects]]
  from = "/privacy-policy.html"
  to = "/privacy-policy/"
  status = 301
  force = true

[[redirects]]
  from = "/affiliate-disclosure.html"
  to = "/affiliate-disclosure/"
  status = 301
  force = true

[[redirects]]
  from = "/es/politica-privacidad.html"
  to = "/es/politica-privacidad/"
  status = 301
  force = true

[[redirects]]
  from = "/es/aviso-afiliados.html"
  to = "/es/aviso-afiliados/"
  status = 301
  force = true

# PRIORITY 8: Category redirects
[[redirects]]
  from = "/categories/*.html"
  to = "/categories/:splat/"
  status = 301
  force = true

[[redirects]]
  from = "/es/categorias/*.html"
  to = "/es/categorias/:splat/"
  status = 301
  force = true

# PRIORITY 9: Category serves (after redirects)
[[redirects]]
  from = "/categories/*/"
  to = "/categories/:splat/index.html"
  status = 200

[[redirects]]
  from = "/es/categorias/*/"
  to = "/es/categorias/:splat/index.html"
  status = 200

# PRIORITY 10: Article serves (after redirects)
[[redirects]]
  from = "/articles/*/"
  to = "/articles/:splat.html"
  status = 200

[[redirects]]
  from = "/es/articulos/*/"
  to = "/es/articulos/:splat.html"
  status = 200

# PRIORITY 11: Main page serves (after redirects)
[[redirects]]
  from = "/privacy-policy/"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/affiliate-disclosure/"
  to = "/affiliate-disclosure.html"
  status = 200

[[redirects]]
  from = "/es/politica-privacidad/"
  to = "/es/politica-privacidad.html"
  status = 200

[[redirects]]
  from = "/es/aviso-afiliados/"
  to = "/es/aviso-afiliados.html"
  status = 200


[[redirects]]
from = "/about.html"
to = "/about/"
status = 301
force = true


[[redirects]]
from = "/contact.html"
to = "/contact/"
status = 301
force = true


[[redirects]]
from = "/terms.html"
to = "/terms/"
status = 301
force = true


[[redirects]]
from = "/es/sobre-nosotros.html"
to = "/es/sobre-nosotros/"
status = 301
force = true


[[redirects]]
from = "/es/contacto.html"
to = "/es/contacto/"
status = 301
force = true


[[redirects]]
from = "/es/terminos.html"
to = "/es/terminos/"
status = 301
force = true
