[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Exclude redirect rules from cache headers
[[headers]]
  for = "/articles/*.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/articulos/*.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/es/articulos/*.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/photos/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules
[[redirects]]
  from = "/articles/*.html"
  to = "/articles/:splat/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/affordable-elegant-casual-handbags-wedding-guest-2025.html"
  to = "/articles/affordable-elegant-casual-handbags-wedding-guest-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/articles/3-rfid-security-wallets-2025.html"
  to = "/articles/3-rfid-security-wallets-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/articulos/*.html"
  to = "/articulos/:splat/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/*.html"
  to = "/es/articulos/:splat/"
  status = 301
  force = true

# Additional Spanish article redirects
[[redirects]]
  from = "/articulos/3-carteras-rfid-seguridad-2025.html"
  to = "/articulos/3-carteras-rfid-seguridad-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/articulos/3-bolsos-panales-funcionales-mamas-2025.html"
  to = "/articulos/3-bolsos-panales-funcionales-mamas-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/3-carteras-rfid-seguridad-2025.html"
  to = "/es/articulos/3-carteras-rfid-seguridad-2025/"
  status = 301
  force = true

[[redirects]]
  from = "/es/articulos/3-bolsos-panales-funcionales-mamas-2025.html"
  to = "/es/articulos/3-bolsos-panales-funcionales-mamas-2025/"
  status = 301
  force = true

